export const FETCH_NEARBY_JOBS_REQUEST = 'FETCH_NEARBY_JOBS_REQUEST'
export const FETCH_NEARBY_JOBS_SUCCESS = 'FETCH_NEARBY_JOBS_SUCCESS'
export const FETCH_NEARBY_JOBS_FAILURE = 'FETCH_NEARBY_JOBS_FAILURE'

export const FETCH_POPULAR_JOBS_REQUEST = 'FETCH_POPULAR_JOBS_REQUEST'
export const FETCH_POPULAR_JOBS_SUCCESS = 'FETCH_POPULAR_JOBS_SUCCESS'
export const FETCH_POPULAR_JOBS_FAILURE = 'FETCH_POPULAR_JOBS_FAILURE'

export const CLOSE_SIDE_MENU = 'CLOSE_SIDE_MENU'
export const OPEN_SIDE_MENU = 'OPEN_SIDE_MENU'

export const FETCH_LOCATION_REQUEST = 'FETCH_LOCATION_REQUEST'
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS'
export const FETCH_LOCATION_FAILURE = 'FETCH_LOCATION_FAILURE'

export const LOCATION_PERMISSION_REQUEST = 'LOCATION_PERMISSION_REQUEST'
export const LOCATION_PERMISSION_GRANTED = 'LOCATION_PERMISSION_GRANTED'
export const LOCATION_PERMISSION_FAILURE = 'LOCATION_PERMISSION_FAILURE'

export const FETCH_GEOCODE_REQUEST = 'FETCH_GEOCODE_REQUEST'
export const FETCH_GEOCODE_SUCCESS = 'FETCH_GEOCODE_SUCCESS'
export const FETCH_GEOCODE_FAILURE = 'FETCH_GEOCODE_FAILURE'