export const FETCH_NEARBY_JOBS_REQUEST = 'FETCH_NEARBY_JOBS_REQUEST'
export const FETCH_NEARBY_JOBS_SUCCESS = 'FETCH_NEARBY_JOBS_SUCCESS'
export const FETCH_NEARBY_JOBS_FAILURE = 'FETCH_NEARBY_JOBS_FAILURE'

export const FETCH_POPULAR_JOBS_REQUEST = 'FETCH_POPULAR_JOBS_REQUEST'
export const FETCH_POPULAR_JOBS_SUCCESS = 'FETCH_POPULAR_JOBS_SUCCESS'
export const FETCH_POPULAR_JOBS_FAILURE = 'FETCH_POPULAR_JOBS_FAILURE'

export const CLOSE_SIDE_MENU = 'CLOSE_SIDE_MENU'
export const OPEN_SIDE_MENU = 'OPEN_SIDE_MENU'